version: 0.1
env:
    secrets-manager:
      TOKEN: sonarqube:sonartoken
phases:
  build:
    commands:
       - mvn verify sonar:sonar -Dsonar.projectKey=devsecops-minfy_devsecops-minfy -Dsonar.organization=devsecops-minfy -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN